### ISSUE TITLE
Wrong response code when InterceptorFlowController.invokeRequestHandlers throws an error

### ISSUE THREAD

**Issue by predic8** [membrane/service-proxy#186] opened 2015-04-14 15:36 UTC
See: https://groups.google.com/forum/#!topic/membrane-monitor/0o6nJqeuOig

**Comment by rrayst** [comment] 2015-08-17 14:49
See discussion in the google group: Throwing IOException closes the TCP connection. Throwing anything else returns 500. This is working as designed.

The problem is some (yet unidentified) component throwing a JsonParseException indirectly extending IOException. 

The JsonParseException should be wrapped in a non-IOException before throwing it.

But as the component is unidentified, I'm closing this bug.

**Closed by rrayst** 2015-08-17 14:49 UTC
Labels: bug, Prio-2
